14 - EFCoreGenericRepository/Blog.Ui/Models/ErrorViewModel.cs
using System;

namespace Blog.Ui.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

14 - EFCoreGenericRepository/Blog.Ui/Controllers/BlogsApiController.cs
//Copyright 2020 (c) SmartIT. All rights reserved. By John Kocer
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using EfCoreGenericRepository.DataAccess;

namespace Blog.Ui.Controllers
{
  [Produces("application/json")]
  [ApiController]
  [Route("api/Blog")]
  public class BlogsApiController : Controller
  {
    private readonly IBlogRepository _blogRepository;

    public BlogsApiController(IBlogRepository blogRepository)
    {
      _blogRepository = blogRepository;

    }

    [Route("~/api/GetBlogs")]
    [HttpGet]
    public async Task<IEnumerable<EfCoreGenericRepository.Models.Blog>> Index()
    {
      return await _blogRepository.GetAllAsyn();
    }

    [Route("~/api/AddBlog")]
    [HttpPost]
    public async Task<EfCoreGenericRepository.Models.Blog> AddBlog([FromBody]EfCoreGenericRepository.Models.Blog blog)
    {
        await _blogRepository.AddAsyn(blog);
        await _blogRepository.SaveAsync();
      return blog;
    }

    [Route("~/api/UpdateBlog")]
    [HttpPut]
    //public Blog UpdateBlog([FromBody] Blog blog)
    //{
    //  var updated = _blogRepository.Update(blog, blog.BlogId);
    //  return updated;
    //}
    public async Task<EfCoreGenericRepository.Models.Blog> UpdateBlog([FromBody]EfCoreGenericRepository.Models.Blog blog)
    {
      var updated =await  _blogRepository.UpdateAsyn(blog, blog.BlogId);
      return updated;
    }

    [Route("~/api/DeleteBlog/{id}")]
    [HttpDelete]
    public string Delete(int id)
    {
      _blogRepository.Delete(_blogRepository.Get(id));
      return "Employee deleted successfully!";
    }

    protected override void Dispose(bool disposing)
    {
      _blogRepository.Dispose();
      base.Dispose(disposing);
    }
  }
}

14 - EFCoreGenericRepository/Blog.Ui/Controllers/BlogsController.cs
//Copyright 2020 (c) SmartIT. All rights reserved. By John Kocer
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EfCoreGenericRepository.DataAccess;

namespace Blog.Ui.Controllers
{
  public class BlogsController : Controller
  {
    private readonly IBlogRepository _blogRepository;

    public BlogsController(IBlogRepository blogRepository)
    {
      _blogRepository = blogRepository;
    }

    public async Task<IActionResult> Index()
    {
      return View(await _blogRepository.GetAllAsyn());
    }

    public IActionResult Create()
    {
      return View();
    }

    public IActionResult Details(int id)
    {
      var blogDetail = _blogRepository.Find(b => b.BlogId == id);
      return View(blogDetail);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Title")]EfCoreGenericRepository.Models.Blog blog)
    {
      if (ModelState.IsValid)
      {
        await _blogRepository.AddAsyn(blog);
        await _blogRepository.SaveAsync();
        return RedirectToAction("Index");
      }
      return View(blog);
    }

    public ActionResult Edit(int? id)
    {
      if (id == null)
        return RedirectToAction("Index");

      EfCoreGenericRepository.Models.Blog blog = _blogRepository.Get((int)id);
      return View(blog);

    }

    [HttpPost]
    public ActionResult Edit([Bind("BlogId,CreatedBy,CreatedOn,Title,UpdatedBy,UpdatedOn")]EfCoreGenericRepository.Models.Blog blog)
    {
      if (ModelState.IsValid)
      {
        _blogRepository.Update(blog, blog.BlogId);
        return RedirectToAction("Index");
      }
      return View(blog);
    }

    public ActionResult Delete(int? id)
    {
      if (id == null)
      {
        return RedirectToAction("Index");
      }

      EfCoreGenericRepository.Models.Blog blog = _blogRepository.Get((int)id);
      if (blog == null)
      {
        return RedirectToAction("Index");
      }
      return View(blog);
    }

    [HttpPost]
    public async Task<IActionResult> Delete(int id)
    {
      EfCoreGenericRepository.Models.Blog blog = _blogRepository.Get(id);
      _blogRepository.Delete(blog);
      return RedirectToAction("Index");
    }

    protected override void Dispose(bool disposing)
    {
      _blogRepository.Dispose();
      base.Dispose(disposing);
    }
  }
}

14 - EFCoreGenericRepository/Blog.Ui/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Blog.Ui.Models;

namespace Blog.Ui.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

14 - EFCoreGenericRepository/Blog.Ui/Views/Blogs/Create.cshtml
@model EfCoreGenericRepository.Models.Blog

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Blog</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                <input asp-for="CreatedBy" class="form-control" />
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>*@
            @*<div class="form-group">
                <label asp-for="UpdatedBy" class="control-label"></label>
                <input asp-for="UpdatedBy" class="form-control" />
                <span asp-validation-for="UpdatedBy" class="text-danger"></span>
            </div>*@
            @*<div class="form-group">
                <label asp-for="UpdatedAt" class="control-label"></label>
                <input asp-for="UpdatedAt" class="form-control" />
                <span asp-validation-for="UpdatedAt" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

14 - EFCoreGenericRepository/Blog.Ui/Views/Blogs/Delete.cshtml
@model EfCoreGenericRepository.Models.Blog

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Blog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedOn)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

14 - EFCoreGenericRepository/Blog.Ui/Views/Blogs/Details.cshtml
@model EfCoreGenericRepository.Models.Blog

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Blog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedOn)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BlogId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

14 - EFCoreGenericRepository/Blog.Ui/Views/Blogs/Edit.cshtml
@model EfCoreGenericRepository.Models.Blog

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Blog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BlogId)

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.UpdatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 ">
                @Html.DisplayFor(model => model.UpdatedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

14 - EFCoreGenericRepository/Blog.Ui/Views/Blogs/Index.cshtml
@model IEnumerable<EfCoreGenericRepository.Models.Blog>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedBy)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UpdatedBy)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UpdatedOn)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedOn)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.BlogId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.BlogId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.BlogId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

14 - EFCoreGenericRepository/Blog.Ui/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>
Copyright 2020 (c) SmartIT. All rights reserved. By John Kocer

14 - EFCoreGenericRepository/Blog.Ui/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

14 - EFCoreGenericRepository/Blog.Ui/Views/Home/Index.cshtml
<html>
<head>
  <title>SmartIT Blog Manager </title>

  <script src="https://code.jquery.com/jquery-3.2.1.min.js"
          integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
          crossorigin="anonymous"></script>

  <script>

    $(document).ready(function () {
      getBlogList();
    });

    var Blog = {
      blogId: 0,
      title: "",
      createdBy: "",
      createdOn: null,
      updatedBy: "",
      updatedOn: null
    }

    // Get all blogs to display
    function getBlogList() {
      // Call Web API to get a list of blogs
      $.ajax({
        url: '/api/GetBlogs/',
        type: 'GET',
        dataType: 'json',
        success: function (blogs) {
          blogListSuccess(blogs);
        },
        error: function (request, message, error) {
          handleException(request, message, error);
        }
      });
    }

    // Display all blogs returned from Web API call
    function blogListSuccess(blogs) {
      // Iterate over the collection of data
      $("#blogTable tbody").remove();
      $.each(blogs, function (index, blog) {
        // Add a row to the blog table
        blogAddRow(blog);
      });
    }

    // Add blog row to <table>
    function blogAddRow(blog) {
      // First check if a <tbody> tag exists, add one if not
      if ($("#blogTable tbody").length == 0) {
        $("#blogTable").append("<tbody></tbody>");
      }

      // Append row to <table>
      $("#blogTable tbody").append(
        blogBuildTableRow(blog));
    }

    // Build a <tr> for a row of table data
    function blogBuildTableRow(blog) {
      var newRow = "<tr>" +
        "<td>" + blog.blogId + "</td>" +
        "<td><input   class='input-title' type='text' value='" + blog.title + "'/></td>" +
        "<td><label   >" + blog.createdBy + "</label></td>" +
        "<td><label   >" + blog.createdOn + "</label></td>" +
        "<td><label   >" + blog.updatedBy + "</label></td>" +
        "<td><label   >" + blog.updatedOn + "</label></td>" +
        "<td>" +
        "<button type='button' " +
        "onclick='blogUpdate(this);' " +
        "class='btn btn-default' " +
        "data-id='" + blog.blogId + "' " +
        //"data-name='" + blog.name + "' " +
        //"data-gender='" + blog.gender + "' " +
        //"data-salary='" + blog.salary + "' " +
        ">" +
        "<span class='glyphicon glyphicon-edit' /> Update" +
        "</button> " +
        " <button type='button' " +
        "onclick='blogDelete(this);'" +
        "class='btn btn-default' " +
        "data-id='" + blog.blogId + "'>" +
        "<span class='glyphicon glyphicon-remove' />Delete" +
        "</button>" +
        "</td>" +
        "</tr>";

      return newRow;
    }

    function onAddBlog(item) {
      var options = {};
      options.url = "/api/AddBlog";
      options.type = "POST";
      var obj = Blog;
      obj.id = 0;
      obj.title = $("#title").val();
      //obj.gender = $("#gender").val();
      //obj.salary = $("#salary").val();
      console.log('in onAddBlog');
      //console.dir(obj);
      options.data = JSON.stringify(obj);
      console.log(options.data);
      options.contentType = "application/json";
      options.dataType = "html";

      options.success = function (msg) {
        getBlogList();
        $("#msg").html(msg);
        $("#title").val("");
      },
        options.error = function () {
          $("#msg").html("Error while calling the Web API!");
        };
      $.ajax(options);
    }

    function blogUpdate(item) {
      var id = $(item).data("id");
      var options = {};
      options.url = "/api/UpdateBlog/"
      options.type = "PUT";

      var obj = Blog;
      obj.blogId = id;
      obj.title = $(".input-title", $(item).parent().parent()).val();
      //obj.gender = $(".input-gender", $(item).parent().parent()).val();
      //obj.salary = $(".input-salary", $(item).parent().parent()).val();
      console.log("blogUpdate id: " +id);
      console.dir(obj);
      options.data = JSON.stringify(obj);
      options.contentType = "application/json";
      options.dataType = "json";
      options.success = function (msg) {
        getBlogList();
        $("#msg").html(msg);
      };
      options.error = function () {
        $("#msg").html("Error while calling the Web API!");
      };
      $.ajax(options);
    }

    function blogDelete(item) {
      var id = $(item).data("id");
      var options = {};
      options.url = "/api/DeleteBlog/"
        + id;
      options.type = "DELETE";
      options.dataType = "html";
      options.success = function (msg) {
        console.log('msg= ' + msg);
        $("#msg").html(msg);
        getBlogList();
      };
      options.error = function () {
        $("#msg").html("Error while calling the Web API!");
      };
      $.ajax(options);
    }

    // Handle exceptions from AJAX calls
    function handleException(request, message, error) {
      var msg = "";
      msg += "Code: " + request.status + "\n";
      msg += "Text: " + request.statusText + "\n";
      if (request.responseJSON != null) {
        msg += "Message" + request.responseJSON.Message + "\n";
      }

      alert(msg);
    }
  </script>
</head>
<body>
  <h3>Blog Manager</h3>
  <form>
    <table id="blogTable" class="table" style="border: 1px solid #999" cellpadding="1">
      <thead>
        <tr style="border: 1px solid #999" cellpadding="1">
          <td>Id </td>
          <td> Title </td>
          <td> CreatedBy </td>
          <td> CreatedOn </td>
          <td> UpdatedBy </td>
          <td> UpdatedOn </td>
          <td> </td>
        </tr>
        <tr>
          <td></td>
          <td><input id="title" type="text" /></td>
          <td><input type="button" id="insert" value="Insert" onclick='onAddBlog(this)' /></td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
      </thead>
    </table>
    <br />
    <div id="msg"></div>
  </form>
</body>
</html>

14 - EFCoreGenericRepository/Blog.Ui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SmartIT- Blog</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SmartIT- Blog</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home-JQuery</a></li>
                    <li><a asp-area="" asp-controller="Blogs" asp-action="Index">Home-MVC</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Copyright 2020 (c) SmartIT. All rights reserved. By John Kocer</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>